import { program } from 'commander';
import Controller from './src/Controller.js';

program
  .name('gephi-converter')
  .description('A tool to convert labeled data sets generated by T.EX to a GEXF file.')
  .version('0.1.0');

program.command('gexf')
  .description('Convert an exported JSON file to a GEXF file.')
  .argument('<dir>', 'path to JSON files')
  .option('-o, --output <file>', 'name of the output file created in current working directory', 'output.gexf')
  .option('--sld', 'in case nodes should be second level domains instead of fully qualified domain names')
  .option('-fp, --first-party', 'include first-party requests to generate nodes and edges')
  .option('-s, --silent', 'disable progress indicator printing on console')
  .action(Controller.gexf);

program.parse();